# Project identification
sonar.projectKey=ecom-engine
sonar.projectName=ecom-engine
sonar.projectVersion=1.0

# Source and Test directories
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go

# Exclusions
sonar.exclusions=**/vendor/**,tmp/**,.git/**,deployments/**,**/*_test.go

# Language settings (Go)
sonar.go.coverage.reportPaths=coverage.out

# Quality Gate enforcement
sonar.qualitygate.wait=true

