/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: "category",
      label: "Getting Started",
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "getting-started" }],
    },
    {
      type: "category",
      label: "Engine",
      items: [{ type: "autogenerated", dirName: "engine" }],
    },
    {
      type: "category",
      label: "Modules",
      items: [{ type: "autogenerated", dirName: "modules" }],
    },
    {
      type: "category",
      label: "API Gateway",
      items: [{ type: "autogenerated", dirName: "gateway" }],
    },
    {
      type: "category",
      label: "Infrastructure",
      items: [{ type: "autogenerated", dirName: "infrastructure" }],
    },
    {
      type: "category",
      label: "Ops & Deploy",
      items: [{ type: "autogenerated", dirName: "ops-deploy" }],
    },
    {
      type: "category",
      label: "Observability",
      items: [{ type: "autogenerated", dirName: "observability" }],
    },
    {
      type: "category",
      label: "pkg - Shared Libraries",
      items: [{ type: "autogenerated", dirName: "pkg" }],
    },
    {
      type: "category",
      label: "Testing",
      items: [{ type: "autogenerated", dirName: "testing" }],
    },
    {
      type: "category",
      label: "Contributing",
      items: [{ type: "autogenerated", dirName: "contributing" }],
    },
    {
      type: "doc",
      id: "changelog",
      label: "Changelog",
    },
  ],
};

export default sidebars;
